#!/usr/bin/env bash
# PreToolUse(Edit|Write|MultiEdit): deny edits to build-generated files.
# These are regenerated by `npm run rm:autocompletes` on every build, so any
# manual edit is clobbered. Edit the source that produces them instead.

input=$(cat)
f=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')

case "$f" in
  *auto-imports.d.ts | *auto-imports.json | *components.d.ts)
    jq -cn '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Generated file — regenerated by `npm run rm:autocompletes` on every build. Edit the source that registers the symbol/component, not this file."}}'
    ;;
esac
exit 0
