/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/clients/': RouteRecordInfo<
      '/admin/clients/',
      '/admin/clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/clients/[id]': RouteRecordInfo<
      '/admin/clients/[id]',
      '/admin/clients/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/areas/': RouteRecordInfo<
      '/areas/',
      '/areas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bookings/': RouteRecordInfo<
      '/bookings/',
      '/bookings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/customers/': RouteRecordInfo<
      '/customers/',
      '/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/customers/[id]': RouteRecordInfo<
      '/customers/[id]',
      '/customers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/customers/new': RouteRecordInfo<
      '/customers/new',
      '/customers/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/deliveries/': RouteRecordInfo<
      '/deliveries/',
      '/deliveries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employees/': RouteRecordInfo<
      '/employees/',
      '/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employees/[id]': RouteRecordInfo<
      '/employees/[id]',
      '/employees/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/expenses/': RouteRecordInfo<
      '/expenses/',
      '/expenses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot-password': RouteRecordInfo<
      '/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/': RouteRecordInfo<
      '/maintenance/',
      '/maintenance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products/': RouteRecordInfo<
      '/products/',
      '/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sales/': RouteRecordInfo<
      '/sales/',
      '/sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vehicles/': RouteRecordInfo<
      '/vehicles/',
      '/vehicles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/clients/index.vue': {
      routes:
        | '/admin/clients/'
      views:
        | never
    }
    'src/pages/admin/clients/[id].vue': {
      routes:
        | '/admin/clients/[id]'
      views:
        | never
    }
    'src/pages/areas/index.vue': {
      routes:
        | '/areas/'
      views:
        | never
    }
    'src/pages/bookings/index.vue': {
      routes:
        | '/bookings/'
      views:
        | never
    }
    'src/pages/customers/index.vue': {
      routes:
        | '/customers/'
      views:
        | never
    }
    'src/pages/customers/[id].vue': {
      routes:
        | '/customers/[id]'
      views:
        | never
    }
    'src/pages/customers/new.vue': {
      routes:
        | '/customers/new'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/deliveries/index.vue': {
      routes:
        | '/deliveries/'
      views:
        | never
    }
    'src/pages/employees/index.vue': {
      routes:
        | '/employees/'
      views:
        | never
    }
    'src/pages/employees/[id].vue': {
      routes:
        | '/employees/[id]'
      views:
        | never
    }
    'src/pages/expenses/index.vue': {
      routes:
        | '/expenses/'
      views:
        | never
    }
    'src/pages/forgot-password.vue': {
      routes:
        | '/forgot-password'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/maintenance/index.vue': {
      routes:
        | '/maintenance/'
      views:
        | never
    }
    'src/pages/products/index.vue': {
      routes:
        | '/products/'
      views:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
    }
    'src/pages/sales/index.vue': {
      routes:
        | '/sales/'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/vehicles/index.vue': {
      routes:
        | '/vehicles/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
