export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  ADMIN_CLIENTS: '/admin/clients',
  ADMIN_CLIENT_DETAIL: (id: string) => `/admin/clients/${id}`,
  RIDERS: '/riders',
  BOOKINGS: '/bookings',
  CUSTOMERS: '/customers',
  CUSTOMER_DETAIL: (id: string) => `/customers/${id}`,
  CUSTOMER_NEW: '/customers/new',
  CUSTOMER_EDIT: (id: string) => `/customers/new?id=${id}`,
  DELIVERIES: '/deliveries',
  EMPLOYEES: '/employees',
  EMPLOYEE_DETAIL: (id: string) => `/employees/${id}`,
  EXPENSES: '/expenses',
  MAINTENANCE: '/maintenance',
  PRODUCTS: '/products',
  SALES: '/sales',
  SETTINGS: '/settings',
  VEHICLES: '/vehicles',
} as const;
